In [1]:
import torch

In [24]:
# matrix
t3 = torch.tensor([[2, 6], 
                   [8, 9], 
                   [9, 4]])                   
t3=torch.tensor(t3,dtype=torch.int)
t3

C:\Users\dllab.DLL-038\AppData\Local\Temp\ipykernel_1684\2597801174.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t3=torch.tensor(t3,dtype=torch.int)


tensor([[2, 6],
        [8, 9],
        [9, 4]], dtype=torch.int32)

In [25]:
t4= torch.tensor([[9,9,8], 
                   [2,6,9]]
                   )
t4=torch.tensor(t4,dtype=torch.int)                   
t4

C:\Users\dllab.DLL-038\AppData\Local\Temp\ipykernel_1684\2549640077.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t4=torch.tensor(t4,dtype=torch.int)


tensor([[9, 9, 8],
        [2, 6, 9]], dtype=torch.int32)

In [27]:
t5=[[0,0,0],[0,0,0],[0,0,0]]
t5=torch.tensor(t5,dtype=torch.int)

In [28]:
for i in range(len(a)):
    for j in range (len(b[0])):
        for k in range (len(b)):
            t5[i][j]+= t3[i][k]*t4[k][j]

In [29]:
t5

tensor([[ 30,  54,  70],
        [ 90, 126, 145],
        [ 89, 105, 108]], dtype=torch.int32)

In [31]:
#inverse of matrix
A=[[1,0,1],[0,1,1],[1,1,1]]
A=torch.tensor(A,dtype=torch.int)
A

tensor([[1, 0, 1],
        [0, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [32]:
f,h=A.shape
f


3

In [33]:
import numpy as np

In [34]:
I = np.identity(n=f)
I=torch.tensor(I,dtype=torch.int)

In [35]:
M = np.concatenate((A,I),axis=1)
M=torch.tensor(M,dtype=torch.int)
M

tensor([[1, 0, 1, 1, 0, 0],
        [0, 1, 1, 0, 1, 0],
        [1, 1, 1, 0, 0, 1]], dtype=torch.int32)

In [37]:
for i in range (0,f):
    pivot = M[i][i]
    row =M[i]
    M[i] = row / pivot
    for j in [k for k in range(0,f) if k!=i]:
        M[j] = M[j]-M[i]*M[j][i]
    inverse = M[:,f:]

inverse

tensor([[ 0, -1,  1],
        [-1,  0,  1],
        [ 1,  1, -1]], dtype=torch.int32)