In [1]:
import torch
#check GPU availability
gpu_avail = torch.cuda.is_available()
print(f"Is the GPU available? {gpu_avail}")

Is the GPU available? False


In [2]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print("Device", device)

Device cpu


In [3]:
a = torch.rand(2,2)
b = torch.rand(2,2)

In [4]:
c = a+b
print(c)

tensor([[1.1485, 1.7811],
        [0.6971, 0.6029]])


In [5]:
d = torch.add(a,b)
print(d)

tensor([[1.1485, 1.7811],
        [0.6971, 0.6029]])


In [10]:
a.add_(1)

tensor([[19.8458, 19.9746],
        [19.6364, 19.0467]])

In [11]:
print(a*b)

tensor([[ 6.0085, 16.1099],
        [ 1.1931, 10.5934]])


In [12]:
a.mul(b)

tensor([[ 6.0085, 16.1099],
        [ 1.1931, 10.5934]])

In [14]:
x = torch.rand(10,10)
y = torch.rand(10,10)
x.matmul(y)

tensor([[1.9511, 1.5151, 1.8198, 2.0944, 1.6413, 1.0410, 2.3846, 2.3947, 2.6045,
         2.3223],
        [1.6936, 1.3180, 1.7435, 2.1687, 2.0877, 1.2509, 2.1500, 2.3969, 2.3915,
         2.2954],
        [2.9972, 2.2464, 2.5630, 2.9003, 2.3205, 1.7989, 2.7582, 2.9367, 3.0301,
         3.3997],
        [2.8439, 2.3823, 3.2149, 3.5516, 2.9222, 2.3081, 3.1768, 3.5114, 3.5044,
         3.7183],
        [2.5516, 2.6006, 2.5805, 2.2055, 2.1392, 2.0443, 2.8390, 2.7164, 2.6137,
         3.6044],
        [2.7379, 2.6982, 2.8974, 2.3379, 2.5519, 2.3102, 3.5474, 3.0394, 3.2631,
         3.8310],
        [2.7268, 2.0028, 2.2796, 2.6423, 2.7096, 2.2561, 2.6562, 2.8209, 2.5406,
         3.3295],
        [1.9846, 2.0062, 2.0990, 1.7909, 2.3995, 1.9070, 2.5756, 2.3590, 2.3192,
         2.9604],
        [2.5124, 2.5211, 2.9483, 2.6946, 3.1372, 2.4576, 3.4030, 3.3137, 3.3304,
         3.8113],
        [2.5804, 2.3415, 2.9751, 2.5996, 2.4636, 2.2270, 3.4207, 2.9245, 3.2528,
         3.6794]])

In [15]:
import numpy as np

In [16]:
l = [1,2,3,4,5]
m = np.array(l)

In [18]:
arr = torch.from_numpy(m)
print(l)

[1, 2, 3, 4, 5]


In [19]:
m

array([1, 2, 3, 4, 5])

In [20]:
f=torch.zeros(2,3,dtype=torch.float64)
print(f)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [21]:
n=torch.tensor([5,6,7],dtype=torch.float)
o=torch.tensor([1,2,3],dtype=torch.float)
print(n+o)

tensor([ 6.,  8., 10.])


In [23]:
torch.add(o,n,out=c)
print(c)

tensor([ 6.,  8., 10.])


C:\Users\HP\AppData\Local\Temp\ipykernel_8344\3997074359.py:1: UserWarning: An output with one or more elements was resized since it had shape [2, 2], which does not match the required output shape [3]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Resize.cpp:24.)
  torch.add(o,n,out=c)


In [24]:
torch.add(n,o).sum()

tensor(24.)