COMPLEX NUMBERS

In [1]:
import torch
import tensorflow as tf
x = torch.randn(2,2, dtype=torch.cfloat)
x

tensor([[-1.1152-1.2457j, -0.3880-0.2175j],
        [ 0.4308+0.5885j, -0.3234-0.2657j]])

In [2]:
x = torch.randn(3, 2)
x

tensor([[ 0.0061,  2.7918],
        [ 0.1782,  0.8926],
        [-0.8650,  0.2286]])

In [3]:
y = torch.view_as_complex(x)
y

tensor([ 0.0061+2.7918j,  0.1782+0.8926j, -0.8650+0.2286j])

In [4]:
torch.view_as_real(y)


tensor([[ 0.0061,  2.7918],
        [ 0.1782,  0.8926],
        [-0.8650,  0.2286]])

MATRIX operation


In [5]:
import torch
import tensorflow as tf

In [6]:
# matrix
t3 = torch.tensor([[2., 6], 
                   [8, 9], 
                   [9, 4]])
t3

tensor([[2., 6.],
        [8., 9.],
        [9., 4.]])

In [7]:
t5=torch.transpose(t3, 0,1)

In [8]:
t5

tensor([[2., 8., 9.],
        [6., 9., 4.]])

In [9]:
t3@t5

tensor([[ 40.,  70.,  42.],
        [ 70., 145., 108.],
        [ 42., 108.,  97.]])

MATRIX MULTIPLICATION