In [2]:
import torch
import tensorflow as tf

In [60]:
# matrix
t3 = torch.tensor([[2., 6], 
                   [8, 9], 
                   [9, 4]])
t3

tensor([[2., 6.],
        [8., 9.],
        [9., 4.]])

In [67]:
t4= torch.tensor([[9.,9.,8.], 
                   [2.,6.,9.]]
                   )
t4

tensor([[9., 9., 8.],
        [2., 6., 9.]])

In [68]:
t5=t3@t4
t5

tensor([[ 30.,  54.,  70.],
        [ 90., 126., 145.],
        [ 89., 105., 108.]])

In [69]:
det = torch.linalg.det(t5)
print("Determinant: \n", det)


Determinant: 
 tensor(0.0035)


In [70]:
A=t5.adjoint()
A

tensor([[ 30.,  90.,  89.],
        [ 54., 126., 105.],
        [ 70., 145., 108.]])

In [71]:
inverse=(1/det)*A

In [72]:
inverse

tensor([[ 8481.9082, 25445.7266, 25162.9961],
        [15267.4355, 35624.0156, 29686.6797],
        [19791.1191, 40995.8906, 30534.8711]])